# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181026_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='index',
            field=models.IntegerField(default=0, verbose_name='index'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='perent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CatalogItem', verbose_name='perent'),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CatalogItem', verbose_name='catalog '),
        ),
    ]
